### ISSUE TITLE
kubeconfig from string?

### ISSUE THREAD

**Issue by dnaeon** [spiegela/concourse-kubernetes-resource#1]
Hi,

Thanks for making this Concourse resource!

Would it be possible to add support for providing a kubeconfig directly as a string in the parameters?

This would make it possible to provide the kubeconfig as part of any secret engine that is used by Concourse.

Thanks!

**Comment by spiegela** [comment]
@dnaeon I can add it to as a parameter to for `get` or `put` requests; however, there is no way to supply a param for a `check` request.

Do you think it would be better to support passing it as a param and loose the ability to `check` the resource, or perhaps I could add it a `kubeconfig` string representation to the `source` block of the resource.  You could set it through `load_vars` or `set_pipeline`.

**Comment by dnaeon** [comment]
Hey @spiegela ,

[load_var](https://concourse-ci.org/jobs.html#load-var-step) and [set_pipeline](https://concourse-ci.org/jobs.html#schema.step.set-pipeline-step.set_pipeline) seem to be experimental features (`set_pipeline` could be gone in the future as well) according to the documentation. Also, they won't work on older Concourse versions.

I was thinking more about being able to specify configuration like this.

```yaml
resources:
- name: myapp
  type: kubernetes
  source:
    kubeconfig: |
      apiVersion: v1
      clusters:
        - cluster:
    ...
    namespace: my-namespace-name
    objects:
      - kind: namespace
        name: my-namespace-name
   ...
```

Generally, I would put the whole `kubeconfig` contents in a secret, so it would like this.

```yaml
resources:
- name: myapp
  type: kubernetes
  source:
    kubeconfig: ((my_kubeconfig))
    namespace: my-namespace-name
    objects:
      - kind: namespace
        name: my-namespace-name
   ...
```

Then from the actual resource scripts we could set the k8s configuration in a similar way.

```bash
#
# Error checks omitted, just for clarity here.
#
KUBECONFIG=$( mktemp kubeconfig.XXXXXX )
export KUBECONFIG

kubeconfig=$( jq -r '.source.kubeconfig // ""' < "$payload" )
echo $kubeconfig > $KUBECONFIG
...
```

Does it make sense to have it this way?

Thanks!
